version: '3.5'

volumes:
  database_data:
    driver: local

services:
  postgres:
    image: postgres:10.6-alpine
    restart: always
    environment:
      - POSTGRES_DB=notipush-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notipush-password
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  server:
    build:
      context: .
    command: yarn start:watch
    ports:
      - "8081:8081"
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_PASSWORD=notipush-password
    links:
     - postgres
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
